apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: YWRhYTY0YzY0M2M2ZmZlZTc3MjkzZGJmYTgwNjk5NTdmOGVkZmZhOWFjNWYxYTkzYzEwZjFiOTg0MDg3ZmZkNjQwZDZjNTQ3YzRjMmYwZjZmZDMzN2Q3ZjhlOGZkMDgxMWJjOTZlYjU1NWE5NjY4ODRjYmExYWQ4M2FmMDY4ZmRkODhlNjhiMTA5MGFmZTM1MDVjNTBkZmVhNzA3ZmI1MjlhZTg1OWM0Njg1NDY5ZDRlOGUzOGQ2OWFhODdlMmVhMmRlYzNhYjJkNWY2MTBjZGUxZWY5Y2M2MDAxYzc0YThiZDU1ZjkxZDhjMWQ2MjkxMjcwNzE5ODE2MzEzMjNiNTc5MWM1MDc4MzA1ZDc1ZjNmYTRkNTk1Njg3ZDhlNjRmODg3NzVmZjBiZTY1MDU4ZmU5MmRjOWZlZjcxNjllYWYwMWZlM2MyODczZjg2ODlhMWI4MjBhMTcwZGNkNTYwZTJkODFlMTdjMDFhNTdkZDJkZWM4Mjk1MDVhNzMyYzQ1MDM0NGE1NDFhMTI2OTFhMGFkN2QzOWMwMGFmMWM5NzZmOTJlY2NhN2M4YzcxMmZhNGZhZjM5ODkzMWViMzYwNThjNjI5NTlmODA3MDBkZGYwOWU3YzhhYjQyZTNhZWM0Yjg2YzdjNTZiMjViNGI1MDI2MGU0MDlkZTk4NGI1Y2UK
